/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Bereich = string;
export interface Contact {
  'id' : ContactId,
  'firma' : string,
  'owner' : Principal,
  'name' : string,
  'notizen' : string,
  'verknuepfteTasks' : Array<TaskId>,
  'email' : string,
  'verknuepfteDokumente' : Array<DocumentId>,
  'telefon' : string,
  'rolle' : string,
}
export type ContactId = string;
export interface CostItem {
  'id' : CostItemId,
  'status' : string,
  'owner' : Principal,
  'dokumentId' : [] | [DocumentId],
  'projektId' : ProjectId,
  'betrag' : number,
  'kategorie' : string,
  'beschreibung' : string,
  'datum' : Time,
  'handwerker' : [] | [string],
}
export type CostItemId = string;
export interface Document {
  'id' : DocumentId,
  'typ' : string,
  'status' : string,
  'bereich' : Bereich,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'name' : string,
}
export type DocumentId = string;
export type ExternalBlob = Uint8Array;
export interface HelpfulLink {
  'id' : LinkId,
  'url' : string,
  'titel' : string,
  'owner' : Principal,
  'logoUrl' : string,
  'kategorie' : string,
  'beschreibung' : string,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface InviteCode__1 { 'code' : string, 'role' : UserRole }
export type InviteToken = string;
export interface KostenUebersicht {
  'offen' : number,
  'gesamt' : number,
  'bezahlt' : number,
}
export type LinkId = string;
export interface Media {
  'id' : MediaId,
  'typ' : string,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'name' : string,
  'tags' : Array<string>,
  'kategorie' : string,
  'position' : bigint,
}
export type MediaId = string;
export interface MediaPositionUpdate {
  'newPosition' : bigint,
  'mediaId' : MediaId,
}
export interface MediaUpdate {
  'typ' : [] | [string],
  'name' : [] | [string],
  'tags' : [] | [Array<string>],
  'kategorie' : [] | [string],
  'position' : [] | [bigint],
}
export interface Project {
  'id' : ProjectId,
  'endDate' : [] | [Time],
  'owner' : Principal,
  'name' : string,
  'color' : string,
  'verantwortlicherKontakt' : [] | [ContactId],
  'kategorie' : string,
  'parentProjectId' : [] | [ProjectId],
  'kunde' : string,
  'startDate' : [] | [Time],
}
export type ProjectId = string;
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Task {
  'id' : TaskId,
  'status' : string,
  'titel' : string,
  'bereich' : Bereich,
  'owner' : Principal,
  'verantwortlicherKontakt' : [] | [ContactId],
  'projectId' : [] | [ProjectId],
  'kategorie' : string,
  'faelligkeit' : Time,
  'dringlichkeit' : bigint,
  'beschreibung' : string,
  'gewerke' : string,
}
export type TaskId = string;
export interface TeamMember { 'principal' : Principal, 'role' : UserRole }
export type Time = bigint;
export interface UserProfile {
  'userType' : UserType,
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserType = { 'business' : null } |
  { 'privat' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addKostenpunkt' : ActorMethod<[ProjectId, CostItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateMediaPositions' : ActorMethod<
    [Array<MediaPositionUpdate>],
    undefined
  >,
  'claimInviteToken' : ActorMethod<[InviteToken], undefined>,
  'createContact' : ActorMethod<
    [
      ContactId,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<TaskId>,
      Array<DocumentId>,
    ],
    undefined
  >,
  'createHelpfulLink' : ActorMethod<
    [LinkId, string, string, string, string, string],
    undefined
  >,
  'createInvite' : ActorMethod<[string, UserRole], undefined>,
  'createInviteToken' : ActorMethod<[UserRole], InviteToken>,
  'createProjekt' : ActorMethod<
    [
      ProjectId,
      string,
      [] | [string],
      string,
      [] | [Time],
      [] | [Time],
      string,
      [] | [ContactId],
      Array<CostItem>,
      [] | [ProjectId],
    ],
    undefined
  >,
  'createTask' : ActorMethod<
    [
      TaskId,
      string,
      string,
      string,
      string,
      bigint,
      Bereich,
      Time,
      string,
      [] | [ContactId],
      [] | [ProjectId],
    ],
    undefined
  >,
  'deleteContact' : ActorMethod<[ContactId], undefined>,
  'deleteDocument' : ActorMethod<[DocumentId], undefined>,
  'deleteHelpfulLink' : ActorMethod<[LinkId], undefined>,
  'deleteKostenpunkt' : ActorMethod<[ProjectId, CostItemId], undefined>,
  'deleteProjekt' : ActorMethod<[ProjectId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'deleteUserMedia' : ActorMethod<[string], undefined>,
  'filterProjectsByUserType' : ActorMethod<[UserType], Array<Project>>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllHelpfulLinks' : ActorMethod<[], Array<HelpfulLink>>,
  'getAllKostenpunkte' : ActorMethod<[], Array<CostItem>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllUserProjects' : ActorMethod<[], Array<[ProjectId, Project]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContact' : ActorMethod<[ContactId], Contact>,
  'getHelpfulLink' : ActorMethod<[LinkId], HelpfulLink>,
  'getInviteCode' : ActorMethod<[string], [] | [InviteCode__1]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getKostenUebersicht' : ActorMethod<[[] | [ProjectId]], KostenUebersicht>,
  'getKostenpunkteByProjekt' : ActorMethod<[ProjectId], Array<CostItem>>,
  'getKostenpunkteByProjectAndPhases' : ActorMethod<[ProjectId], Array<CostItem>>,
  'getPhasesByProject' : ActorMethod<[ProjectId], Array<Project>>,
  'getProjekt' : ActorMethod<[ProjectId], Project>,
  'getTask' : ActorMethod<[TaskId], Task>,
  'getTopLevelProjects' : ActorMethod<[], Array<Project>>,
  'getUserDocuments' : ActorMethod<[], Array<Document>>,
  'getUserMedia' : ActorMethod<[], Array<Media>>,
  'getMediaByProject' : ActorMethod<[ProjectId], Array<Media>>,
  'getTasksByProject' : ActorMethod<[ProjectId], Array<Task>>,
  'getDocumentsByProject' : ActorMethod<[ProjectId], Array<Document>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'removeTeamMember' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateContact' : ActorMethod<
    [
      ContactId,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<TaskId>,
      Array<DocumentId>,
    ],
    undefined
  >,
  'updateHelpfulLink' : ActorMethod<
    [LinkId, string, string, string, string, string],
    undefined
  >,
  'updateKostenpunkt' : ActorMethod<
    [ProjectId, CostItemId, CostItem],
    undefined
  >,
  'updateMedia' : ActorMethod<[string, MediaUpdate], undefined>,
  'updateProjekt' : ActorMethod<
    [
      ProjectId,
      string,
      [] | [string],
      string,
      [] | [Time],
      [] | [Time],
      string,
      [] | [ContactId],
      Array<CostItem>,
    ],
    undefined
  >,
  'updateTask' : ActorMethod<
    [
      TaskId,
      string,
      string,
      string,
      string,
      bigint,
      Bereich,
      Time,
      string,
      [] | [ContactId],
      [] | [ProjectId],
    ],
    undefined
  >,
  'updateTeamMemberRole' : ActorMethod<[Principal, UserRole], undefined>,
  'uploadDocumentWithPDF' : ActorMethod<
    [string, string, Bereich, string, string, ExternalBlob, [] | [ProjectId]],
    undefined
  >,
  'uploadMedia' : ActorMethod<
    [string, string, string, string, bigint, Array<string>, ExternalBlob, [] | [ProjectId]],
    undefined
  >,
  'validateInviteCode' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];