/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Task {
    id: TaskId;
    status: string;
    titel: string;
    bereich: Bereich;
    owner: Principal;
    verantwortlicherKontakt?: ContactId;
    projectId?: ProjectId;
    kategorie: string;
    faelligkeit: Time;
    dringlichkeit: bigint;
    beschreibung: string;
    gewerke: string;
}
export interface Document {
    id: DocumentId;
    typ: string;
    status: string;
    bereich: Bereich;
    owner: Principal;
    blob: ExternalBlob;
    name: string;
}
export interface MediaPositionUpdate {
    newPosition: bigint;
    mediaId: MediaId;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type CostItemId = string;
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export type InviteToken = string;
export interface MediaUpdate {
    typ?: string;
    name?: string;
    tags?: Array<string>;
    kategorie?: string;
    position?: bigint;
}
export type DocumentId = string;
export interface InviteCode__1 {
    code: string;
    role: UserRole;
}
export interface KostenUebersicht {
    offen: number;
    gesamt: number;
    bezahlt: number;
}
export interface Media {
    id: MediaId;
    typ: string;
    owner: Principal;
    blob: ExternalBlob;
    name: string;
    tags: Array<string>;
    kategorie: string;
    position: bigint;
}
export interface Contact {
    id: ContactId;
    firma: string;
    owner: Principal;
    name: string;
    notizen: string;
    verknuepfteTasks: Array<TaskId>;
    email: string;
    verknuepfteDokumente: Array<DocumentId>;
    telefon: string;
    rolle: string;
}
export interface HelpfulLink {
    id: LinkId;
    url: string;
    titel: string;
    owner: Principal;
    logoUrl: string;
    kategorie: string;
    beschreibung: string;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export type Bereich = string;
export type LinkId = string;
export type TaskId = string;
export type ProjectId = string;
export interface CostItem {
    id: CostItemId;
    status: string;
    owner: Principal;
    dokumentId?: DocumentId;
    projektId: ProjectId;
    betrag: number;
    kategorie: string;
    beschreibung: string;
    datum: Time;
    handwerker?: string;
}
export interface TeamMember {
    principal: Principal;
    role: UserRole;
}
export type ContactId = string;
export interface Project {
    id: ProjectId;
    endDate?: Time;
    owner: Principal;
    name: string;
    color: string;
    verantwortlicherKontakt?: ContactId;
    kategorie: string;
    parentProjectId?: ProjectId;
    kunde: string;
    startDate?: Time;
}
export type MediaId = string;
export interface UserProfile {
    userType: UserType;
    name: string;
    role: string;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserType {
    business = "business",
    privat = "privat"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addKostenpunkt(projectId: ProjectId, kost: CostItem): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUpdateMediaPositions(updates: Array<MediaPositionUpdate>): Promise<void>;
    claimInviteToken(token: InviteToken): Promise<void>;
    createContact(id: ContactId, name: string, firma: string, rolle: string, email: string, telefon: string, notizen: string, verknuepfteTasks: Array<TaskId>, verknuepfteDokumente: Array<DocumentId>): Promise<void>;
    createHelpfulLink(id: LinkId, titel: string, beschreibung: string, url: string, kategorie: string, logoUrl: string): Promise<void>;
    createInvite(generatedCode: string, role: UserRole): Promise<void>;
    createInviteToken(role: UserRole): Promise<InviteToken>;
    createProjekt(id: ProjectId, name: string, kunde: string | null, color: string, start: Time | null, end: Time | null, kategorie: string, verantwortlicherKontakt: ContactId | null, costItemsArray: Array<CostItem>, parentProjectId: ProjectId | null): Promise<void>;
    createTask(id: TaskId, titel: string, beschreibung: string, gewerke: string, status: string, dringlichkeit: bigint, bereich: Bereich, faelligkeit: Time, kategorie: string, verantwortlicherKontakt: ContactId | null, projectId: ProjectId | null): Promise<void>;
    deleteContact(contactId: ContactId): Promise<void>;
    deleteDocument(documentId: DocumentId): Promise<void>;
    deleteHelpfulLink(linkId: LinkId): Promise<void>;
    deleteKostenpunkt(projectId: ProjectId, kostenpunktId: CostItemId): Promise<void>;
    deleteProjekt(id: ProjectId): Promise<void>;
    deleteTask(taskId: TaskId): Promise<void>;
    deleteUserMedia(mediaId: string): Promise<void>;
    filterProjectsByUserType(userType: UserType): Promise<Array<Project>>;
    generateInviteCode(): Promise<string>;
    getAllContacts(): Promise<Array<Contact>>;
    getAllHelpfulLinks(): Promise<Array<HelpfulLink>>;
    getAllKostenpunkte(): Promise<Array<CostItem>>;
    getAllProjects(): Promise<Array<Project>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getAllTasks(): Promise<Array<Task>>;
    getAllUserProjects(): Promise<Array<[ProjectId, Project]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContact(contactId: ContactId): Promise<Contact>;
    getDocumentsByProject(projectId: ProjectId): Promise<Array<Document>>;
    getHelpfulLink(linkId: LinkId): Promise<HelpfulLink>;
    getInviteCode(generatedCode: string): Promise<InviteCode__1 | null>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getKostenUebersicht(projektId: ProjectId | null): Promise<KostenUebersicht>;
    getKostenpunkteByProjectAndPhases(projectId: ProjectId): Promise<Array<CostItem>>;
    getKostenpunkteByProjekt(projectId: ProjectId): Promise<Array<CostItem>>;
    getMediaByProject(projectId: ProjectId): Promise<Array<Media>>;
    getPhasesByProject(parentId: ProjectId): Promise<Array<Project>>;
    getProjekt(id: ProjectId): Promise<Project>;
    getTask(taskId: TaskId): Promise<Task>;
    getTasksByProject(projectId: ProjectId): Promise<Array<Task>>;
    getTopLevelProjects(): Promise<Array<Project>>;
    getUserDocuments(): Promise<Array<Document>>;
    getUserMedia(): Promise<Array<Media>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listTeamMembers(): Promise<Array<TeamMember>>;
    removeTeamMember(principal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    updateContact(id: ContactId, name: string, firma: string, rolle: string, email: string, telefon: string, notizen: string, verknuepfteTasks: Array<TaskId>, verknuepfteDokumente: Array<DocumentId>): Promise<void>;
    updateHelpfulLink(id: LinkId, titel: string, beschreibung: string, url: string, kategorie: string, logoUrl: string): Promise<void>;
    updateKostenpunkt(projectId: ProjectId, kostId: CostItemId, updatedKost: CostItem): Promise<void>;
    updateMedia(id: string, updates: MediaUpdate): Promise<void>;
    updateProjekt(id: ProjectId, name: string, kunde: string | null, color: string, start: Time | null, end: Time | null, kategorie: string, verantwortlicherKontakt: ContactId | null, costItemsArray: Array<CostItem>): Promise<void>;
    updateTask(id: TaskId, titel: string, beschreibung: string, gewerke: string, status: string, dringlichkeit: bigint, bereich: Bereich, faelligkeit: Time, kategorie: string, verantwortlicherKontakt: ContactId | null, projectId: ProjectId | null): Promise<void>;
    updateTeamMemberRole(principal: Principal, role: UserRole): Promise<void>;
    uploadDocumentWithPDF(id: string, name: string, bereich: Bereich, typ: string, status: string, blob: ExternalBlob, projectId: ProjectId | null): Promise<void>;
    uploadMedia(id: string, name: string, kategorie: string, typ: string, position: bigint, tags: Array<string>, blob: ExternalBlob, projectId: ProjectId | null): Promise<void>;
    validateInviteCode(generatedCode: string): Promise<void>;
}
import type { Bereich as _Bereich, ContactId as _ContactId, CostItem as _CostItem, CostItemId as _CostItemId, Document as _Document, DocumentId as _DocumentId, ExternalBlob as _ExternalBlob, InviteCode__1 as _InviteCode__1, Media as _Media, MediaId as _MediaId, MediaUpdate as _MediaUpdate, Project as _Project, ProjectId as _ProjectId, Task as _Task, TaskId as _TaskId, TeamMember as _TeamMember, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserType as _UserType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addKostenpunkt(arg0: ProjectId, arg1: CostItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addKostenpunkt(arg0, to_candid_CostItem_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKostenpunkt(arg0, to_candid_CostItem_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUpdateMediaPositions(arg0: Array<MediaPositionUpdate>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateMediaPositions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateMediaPositions(arg0);
            return result;
        }
    }
    async claimInviteToken(arg0: InviteToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimInviteToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimInviteToken(arg0);
            return result;
        }
    }
    async createContact(arg0: ContactId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: Array<TaskId>, arg8: Array<DocumentId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createContact(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContact(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createHelpfulLink(arg0: LinkId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHelpfulLink(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHelpfulLink(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createInvite(arg0: string, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvite(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvite(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createInviteToken(arg0: UserRole): Promise<InviteToken> {
        if (this.processError) {
            try {
                const result = await this.actor.createInviteToken(to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInviteToken(to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProjekt(arg0: ProjectId, arg1: string, arg2: string | null, arg3: string, arg4: Time | null, arg5: Time | null, arg6: string, arg7: ContactId | null, arg8: Array<CostItem>, arg9: ProjectId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProjekt(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), to_candid_vec_n15(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProjekt(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), to_candid_vec_n15(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async createTask(arg0: TaskId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: Bereich, arg7: Time, arg8: string, arg9: ContactId | null, arg10: ProjectId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async deleteContact(arg0: ContactId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteDocument(arg0: DocumentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteHelpfulLink(arg0: LinkId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHelpfulLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHelpfulLink(arg0);
            return result;
        }
    }
    async deleteKostenpunkt(arg0: ProjectId, arg1: CostItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKostenpunkt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKostenpunkt(arg0, arg1);
            return result;
        }
    }
    async deleteProjekt(arg0: ProjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProjekt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProjekt(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteUserMedia(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserMedia(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserMedia(arg0);
            return result;
        }
    }
    async filterProjectsByUserType(arg0: UserType): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProjectsByUserType(to_candid_UserType_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProjectsByUserType(to_candid_UserType_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAllContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return result;
        }
    }
    async getAllHelpfulLinks(): Promise<Array<HelpfulLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHelpfulLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHelpfulLinks();
            return result;
        }
    }
    async getAllKostenpunkte(): Promise<Array<CostItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKostenpunkte();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKostenpunkte();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProjects(): Promise<Array<[ProjectId, Project]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProjects();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProjects();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContact(arg0: ContactId): Promise<Contact> {
        if (this.processError) {
            try {
                const result = await this.actor.getContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContact(arg0);
            return result;
        }
    }
    async getDocumentsByProject(arg0: ProjectId): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentsByProject(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentsByProject(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHelpfulLink(arg0: LinkId): Promise<HelpfulLink> {
        if (this.processError) {
            try {
                const result = await this.actor.getHelpfulLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHelpfulLink(arg0);
            return result;
        }
    }
    async getInviteCode(arg0: string): Promise<InviteCode__1 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCode(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCode(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getKostenUebersicht(arg0: ProjectId | null): Promise<KostenUebersicht> {
        if (this.processError) {
            try {
                const result = await this.actor.getKostenUebersicht(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKostenUebersicht(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getKostenpunkteByProjectAndPhases(arg0: ProjectId): Promise<Array<CostItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKostenpunkteByProjectAndPhases(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKostenpunkteByProjectAndPhases(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKostenpunkteByProjekt(arg0: ProjectId): Promise<Array<CostItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKostenpunkteByProjekt(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKostenpunkteByProjekt(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaByProject(arg0: ProjectId): Promise<Array<Media>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaByProject(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaByProject(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhasesByProject(arg0: ProjectId): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhasesByProject(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhasesByProject(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjekt(arg0: ProjectId): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjekt(arg0);
                return from_candid_Project_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjekt(arg0);
            return from_candid_Project_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: TaskId): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_Task_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_Task_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByProject(arg0: ProjectId): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByProject(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByProject(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopLevelProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopLevelProjects();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopLevelProjects();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDocuments();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDocuments();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMedia(): Promise<Array<Media>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMedia();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMedia();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeamMembers();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeamMembers();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeTeamMember(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTeamMember(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async updateContact(arg0: ContactId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: Array<TaskId>, arg8: Array<DocumentId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContact(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContact(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateHelpfulLink(arg0: LinkId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHelpfulLink(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHelpfulLink(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateKostenpunkt(arg0: ProjectId, arg1: CostItemId, arg2: CostItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKostenpunkt(arg0, arg1, to_candid_CostItem_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKostenpunkt(arg0, arg1, to_candid_CostItem_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateMedia(arg0: string, arg1: MediaUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedia(arg0, to_candid_MediaUpdate_n57(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedia(arg0, to_candid_MediaUpdate_n57(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProjekt(arg0: ProjectId, arg1: string, arg2: string | null, arg3: string, arg4: Time | null, arg5: Time | null, arg6: string, arg7: ContactId | null, arg8: Array<CostItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjekt(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), to_candid_vec_n15(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjekt(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), to_candid_vec_n15(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: Bereich, arg7: Time, arg8: string, arg9: ContactId | null, arg10: ProjectId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async updateTeamMemberRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamMemberRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamMemberRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadDocumentWithPDF(arg0: string, arg1: string, arg2: Bereich, arg3: string, arg4: string, arg5: ExternalBlob, arg6: ProjectId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocumentWithPDF(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n59(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocumentWithPDF(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n59(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async uploadMedia(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: Array<string>, arg6: ExternalBlob, arg7: ProjectId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMedia(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n59(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMedia(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n59(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async validateInviteCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateInviteCode(arg0);
            return result;
        }
    }
}
function from_candid_CostItem_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CostItem): CostItem {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InviteCode__1_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteCode__1): InviteCode__1 {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_Media_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Media): Promise<Media> {
    return await from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_TeamMember_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMember): TeamMember {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserType): UserType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactId]): ContactId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectId]): ProjectId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentId]): DocumentId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InviteCode__1]): InviteCode__1 | null {
    return value.length === 0 ? null : from_candid_InviteCode__1_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    endDate: [] | [_Time];
    owner: Principal;
    name: string;
    color: string;
    verantwortlicherKontakt: [] | [_ContactId];
    kategorie: string;
    parentProjectId: [] | [_ProjectId];
    kunde: string;
    startDate: [] | [_Time];
}): {
    id: ProjectId;
    endDate?: Time;
    owner: Principal;
    name: string;
    color: string;
    verantwortlicherKontakt?: ContactId;
    kategorie: string;
    parentProjectId?: ProjectId;
    kunde: string;
    startDate?: Time;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.endDate)),
        owner: value.owner,
        name: value.name,
        color: value.color,
        verantwortlicherKontakt: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.verantwortlicherKontakt)),
        kategorie: value.kategorie,
        parentProjectId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.parentProjectId)),
        kunde: value.kunde,
        startDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.startDate))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CostItemId;
    status: string;
    owner: Principal;
    dokumentId: [] | [_DocumentId];
    projektId: _ProjectId;
    betrag: number;
    kategorie: string;
    beschreibung: string;
    datum: _Time;
    handwerker: [] | [string];
}): {
    id: CostItemId;
    status: string;
    owner: Principal;
    dokumentId?: DocumentId;
    projektId: ProjectId;
    betrag: number;
    kategorie: string;
    beschreibung: string;
    datum: Time;
    handwerker?: string;
} {
    return {
        id: value.id,
        status: value.status,
        owner: value.owner,
        dokumentId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.dokumentId)),
        projektId: value.projektId,
        betrag: value.betrag,
        kategorie: value.kategorie,
        beschreibung: value.beschreibung,
        datum: value.datum,
        handwerker: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.handwerker))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: string;
    titel: string;
    bereich: _Bereich;
    owner: Principal;
    verantwortlicherKontakt: [] | [_ContactId];
    projectId: [] | [_ProjectId];
    kategorie: string;
    faelligkeit: _Time;
    dringlichkeit: bigint;
    beschreibung: string;
    gewerke: string;
}): {
    id: TaskId;
    status: string;
    titel: string;
    bereich: Bereich;
    owner: Principal;
    verantwortlicherKontakt?: ContactId;
    projectId?: ProjectId;
    kategorie: string;
    faelligkeit: Time;
    dringlichkeit: bigint;
    beschreibung: string;
    gewerke: string;
} {
    return {
        id: value.id,
        status: value.status,
        titel: value.titel,
        bereich: value.bereich,
        owner: value.owner,
        verantwortlicherKontakt: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.verantwortlicherKontakt)),
        projectId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.projectId)),
        kategorie: value.kategorie,
        faelligkeit: value.faelligkeit,
        dringlichkeit: value.dringlichkeit,
        beschreibung: value.beschreibung,
        gewerke: value.gewerke
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: _UserType;
    name: string;
    role: string;
    email: string;
}): {
    userType: UserType;
    name: string;
    role: string;
    email: string;
} {
    return {
        userType: from_candid_UserType_n38(_uploadFile, _downloadFile, value.userType),
        name: value.name,
        role: value.role,
        email: value.email
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DocumentId;
    typ: string;
    status: string;
    bereich: _Bereich;
    owner: Principal;
    blob: _ExternalBlob;
    name: string;
}): Promise<{
    id: DocumentId;
    typ: string;
    status: string;
    bereich: Bereich;
    owner: Principal;
    blob: ExternalBlob;
    name: string;
}> {
    return {
        id: value.id,
        typ: value.typ,
        status: value.status,
        bereich: value.bereich,
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.blob),
        name: value.name
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    code: string;
    role: _UserRole;
}): {
    code: string;
    role: UserRole;
} {
    return {
        code: value.code,
        role: from_candid_UserRole_n40(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MediaId;
    typ: string;
    owner: Principal;
    blob: _ExternalBlob;
    name: string;
    tags: Array<string>;
    kategorie: string;
    position: bigint;
}): Promise<{
    id: MediaId;
    typ: string;
    owner: Principal;
    blob: ExternalBlob;
    name: string;
    tags: Array<string>;
    kategorie: string;
    position: bigint;
}> {
    return {
        id: value.id,
        typ: value.typ,
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        tags: value.tags,
        kategorie: value.kategorie,
        position: value.position
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
}): {
    principal: Principal;
    role: UserRole;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n40(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_tuple_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ProjectId, _Project]): [ProjectId, Project] {
    return [
        value[0],
        from_candid_Project_n20(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    business: null;
} | {
    privat: null;
}): UserType {
    return "business" in value ? UserType.business : "privat" in value ? UserType.privat : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CostItem>): Array<CostItem> {
    return value.map((x)=>from_candid_CostItem_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ProjectId, _Project]>): Array<[ProjectId, Project]> {
    return value.map((x)=>from_candid_tuple_n34(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Promise<Array<Document>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Document_n43(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Media>): Promise<Array<Media>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Media_n50(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamMember>): Array<TeamMember> {
    return value.map((x)=>from_candid_TeamMember_n53(_uploadFile, _downloadFile, x));
}
function to_candid_CostItem_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CostItem): _CostItem {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MediaUpdate_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaUpdate): _MediaUpdate {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): _UserType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactId | null): [] | [_ContactId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectId | null): [] | [_ProjectId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: UserType;
    name: string;
    role: string;
    email: string;
}): {
    userType: _UserType;
    name: string;
    role: string;
    email: string;
} {
    return {
        userType: to_candid_UserType_n17(_uploadFile, _downloadFile, value.userType),
        name: value.name,
        role: value.role,
        email: value.email
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    typ?: string;
    name?: string;
    tags?: Array<string>;
    kategorie?: string;
    position?: bigint;
}): {
    typ: [] | [string];
    name: [] | [string];
    tags: [] | [Array<string>];
    kategorie: [] | [string];
    position: [] | [bigint];
} {
    return {
        typ: value.typ ? candid_some(value.typ) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        tags: value.tags ? candid_some(value.tags) : candid_none(),
        kategorie: value.kategorie ? candid_some(value.kategorie) : candid_none(),
        position: value.position ? candid_some(value.position) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: CostItemId;
    status: string;
    owner: Principal;
    dokumentId?: DocumentId;
    projektId: ProjectId;
    betrag: number;
    kategorie: string;
    beschreibung: string;
    datum: Time;
    handwerker?: string;
}): {
    id: _CostItemId;
    status: string;
    owner: Principal;
    dokumentId: [] | [_DocumentId];
    projektId: _ProjectId;
    betrag: number;
    kategorie: string;
    beschreibung: string;
    datum: _Time;
    handwerker: [] | [string];
} {
    return {
        id: value.id,
        status: value.status,
        owner: value.owner,
        dokumentId: value.dokumentId ? candid_some(value.dokumentId) : candid_none(),
        projektId: value.projektId,
        betrag: value.betrag,
        kategorie: value.kategorie,
        beschreibung: value.beschreibung,
        datum: value.datum,
        handwerker: value.handwerker ? candid_some(value.handwerker) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): {
    business: null;
} | {
    privat: null;
} {
    return value == UserType.business ? {
        business: null
    } : value == UserType.privat ? {
        privat: null
    } : value;
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CostItem>): Array<_CostItem> {
    return value.map((x)=>to_candid_CostItem_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
